### ISSUE TITLE
Welcome to the Autopilot API Forum

### ISSUE THREAD

**Issue by chrissharkey** [autopilotdev/autopilotdev.github.io#1]
We have decided to keep things simple initially and allow everyone to ask their Autopilot API questions on the Github issues forum for our website.

Please post your questions or comments as issues and expect fast replies!

Chris Sharkey.

**Comment by chief-kh** [comment]
Hi
How can I get all contacts using API?

**Comment by chrissharkey** [comment]
Hi Chief-kh,

Here is an article on how to accomplish that using the API:

http://developers.autopilothq.com/getting-contacts-on-a-list-with-bookmarks.html

Chris

**Comment by chief-kh** [comment]
I don't have list id. I need all the contacts displayed on this page:
https://app.autopilothq.com/#contacts/list/all/createdAt/Desc/1

**Comment by chrissharkey** [comment]
In the Autopilot interface:

1) Make a new list
2) Select all contacts on the page you linked
3) Select "Add contacts to list" then add them to the list you created
4) Get that list_id from the url, looks like contactlist_XXXXXXXXX
5) Follow the instructions in the linked blog post

**Comment by chief-kh** [comment]
I'm creating solution for my client for automatic syncing contacts. Can I do all these steps without web interface throw API?

**Comment by chrissharkey** [comment]
Try setting the list_id to all_contacts. Remember you need to do multiple requests using the bookmark. If that doesn't work then I can make that work for you. With that and the bulk add contacts API you should be able to do a full sync.

**Comment by chrissharkey** [comment]
But yes it should be possible without using the web interface.

**Comment by chief-kh** [comment]
Thanks for your help. This URL working fine for me:
https://api2.autopilothq.com/v1/list/contactlist_all/contacts

**Comment by zakholdsworth** [comment]
hey @chrissharkey can we configure a sandbox environment so we can test our integration on our staging servers?

**Comment by chrissharkey** [comment]
Hi Zak,

I believe that Peter answered you, but what we usually recommend is to just start another Autopilot trial and use that as your sandbox. All of the data is stored in completely separate databases, so there is obviously no risk to your primary account, and by testing in this way you know you're dealing with the real thing - and you can test at a large volume.

Just let me know the account name so I can remove all of the limits on it for you.

Chris.

**Comment by zakholdsworth** [comment]
Awesome thanks. We created a new one called Hint Health sandbox. Appreciate
the quick response

**Comment by blakewest** [comment]
Hey @chrissharkey . I'm working with @zakholdsworth at Hint Health. I'm curious, the docs say AutoPilot uses Email as the unique identifier for Contacts. Does this mean we cannot update the email for a contact? Or how would doing that work? Could we explicitly send the contact_id and then change the email address?
