### ISSUE TITLE
ID between Autopilot and Google Analytics

### ISSUE THREAD

**Issue by McDuck4** [autopilotdev/autopilotdev.github.io#10]
Hello everybody

Is there a way where I can get an ID on a visitor from Autopilot over to Google Analytics?

Best Regards

**Comment by Cubatica** [comment]
Hey mate, 

That would be against google analytics TOS and could get your account banned unless you use the google Analytics User-ID and push that through as a hidden field on form submits.

**Comment by chrissharkey** [comment]
Thanks for the answer Blueprint!
