### ISSUE TITLE
Calling a Trigger

### ISSUE THREAD

**Issue by codeaholicman** [autopilotdev/autopilotdev.github.io#11]
Hi,

Everytime I try and call a trigger I just get boolean(false) as the reply. I can add contacts no problem and the trigger works for the debug URL. in production however it just gives me boolean(false).

Any ideas? Ive tried creating a new journey and also new API trigger numbers.

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"https://api2.autopilothq.com/v1/trigger/0026/contact/gamapucoch@thraml.com
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);

curl_setopt($ch, CURLOPT_POST, TRUE);

curl_setopt($ch, CURLOPT_HTTPHEADER, array(
  "autopilotapikey: xxxxxxxxxxxxxxxxxxxxxx"
));

$response = curl_exec($ch);
curl_close($ch);

var_dump($response);

**Comment by chrissharkey** [comment]
Hi, 

If you are still having this problem could you please open another issue. I took so long to follow this up, sorry about that!

Chris.
