### ISSUE TITLE
emails via the API?

### ISSUE THREAD

**Issue by mwindholtz** [autopilotdev/autopilotdev.github.io#12]
The issues here don't seem to have a lot of responses so I'm a bit doubtful if this is the right channel to get autopilot support, but here goes ...

How can I send html formatted emails via the API?
I need to send transactional emails that my RubyOnRails app has already has formatted. 

Can I do this using the API?

**Comment by chrissharkey** [comment]
Yes you can. Following the docs, send your preformatted HTML through in a custom string variable (there's no limit on size) and then upload a HTML template to use which just contains that variable. If you need specific help with this please ask and I can set up a demo pm your account.

If you haven't already you'll need to apply to be able to send transactional emails but it is a quick process

**Comment by MincePie** [comment]
Hi Chris, I'm also struggling with this. I didn't know specific permission was required. Last time I checked, you insisted on using 'unsubscribe' links on transactional email until you hit a very high number of emails sent. Is permission a new thing? How do I apply for permission?

**Comment by chrissharkey** [comment]
Hi MincePie,

Here is the article on transactional emails and permission, including how to apply:

https://autopilothq.zendesk.com/hc/en-us/articles/205674069-Do-I-have-to-use-an-unsubscribe-link-in-my-transactional-emails-

Chris.
