### ISSUE TITLE
Better visit/utm info in GET contact response

### ISSUE THREAD

**Issue by henryhund** [autopilotdev/autopilotdev.github.io#15]
Below I've included a snippet of the API response from the GET contact endpoint. It shows first visit, first form conversion, and then a list of all page visits and utm tags ever. I'm hoping that you can provide better organization to this information.

```
  "first_visit_at": "2016-06-27T15:46:51.165Z",
  "first_conversion_at": "2016-07-15T19:00:05.998Z",
  "anywhere_page_visits": {
    "//optintest.pagedemo.co": true,
    "//staging.xxxxx.com": true,
    "//staging.xxxxx.com/company": true,
    "//staging.xxxxx.com/integrations": true,
    "//staging.xxxxx.com/features": true,
    "//staging.xxxxx.com/pricing": true,
    "//staging.xxxxx.com/integrations/zuora": true,
    "//staging.xxxxx.com/integrations/desk-com": true
  },
  "anywhere_utm": {
    "utm_campaign=test-campaign": true,
    "utm_source=test-source": true,
    "utm_medium=test-medium": true,
    "utm_campaign=test-campaign2": true,
    "utm_source=test-source2": true,
    "utm_medium=test-medium2": true
  },
```

Ideally, I'd like to see the response formatted similarly to the following:

```
"page_visits" {
"date":
{
"page_url":"page_url",
"utm_campaign":"utm_campaign",
"utm_source":"utm_source",
"utm_medium":"utm_medium",
"utm_term":"utm_term",
"utm_content":"utm_content",
"full_querystring":"full_querystring",
"form_viewed":"form_id",
"form_conversion":"form_id"
},
"date2":
...
}
```

This would provide clearer detail of which campaigns impacted form conversions, as well as which campaigns occurred in between funnel steps. The API response right now provides no context of when the campaign/page view occurred, which makes it impossible to use for analysis.

**Comment by chrissharkey** [comment]
Hi Henry,

We won't be making any further updates to our version 1 API except for bug fixes. However, we are in heavy development on v2 of our API which will address issues like the ones you raised and provide far more in depth and organised access to the data which Autopilot stores on your behalf.

Chris.
