### ISSUE TITLE
No way to update contacts that don't have an email?

### ISSUE THREAD

**Issue by efantasia** [autopilotdev/autopilotdev.github.io#16]
I have tried updating existing contacts that have no email address using the "contact_id" field, but this seems to always create a new contact instead of updating the existing contact.

Actually, it seems as though contact_id is never respected for any single or bulk contact update?

**Comment by chrissharkey** [comment]
Hi efantasia,

Currently we use Email as the main key for updating contacts. contact_id is just provided for reference. So yes, this definitely means you would not be able to edit contacts which don't have an email address.

We are working on a new version of our API which will improve many things, this being one of them. For now, this will remain a limitation of the API.

Chris.
