### ISSUE TITLE
Custom Fields for Companies via API

### ISSUE THREAD

**Issue by mattttt** [autopilotdev/autopilotdev.github.io#17]
Hello,

In the interface, I'm able to add custom fields on a Company level, but it does not appear available via the API. Could it be an undocumented method you can shed some light on?

Thanks,
Matt

**Comment by DanCech** [comment]
+1

**Comment by mattttt** [comment]
Hi Autopilot - is Github still the correct place for requests like these? Total lack of response is disheartening. 

cc: @chrissharkey

**Comment by petersharkey** [comment]
Hi @mattttt @DanCech apologies for the delay. This is not currently possible, however I'd encourage you to submit this idea to our API feedback forum: https://autopilothq.uservoice.com/forums/305698-api-feedback-forum. Regarding requests, yes it's the correct place and we're in the process of expanding our API team so we can be more responsive. In the meantime, support [at] autopilothq.com can also answer API related questions.
