### ISSUE TITLE
session id to contact

### ISSUE THREAD

**Issue by McDuck4** [autopilotdev/autopilotdev.github.io#18]
Hello Everybody.

I am struggling to understand and program the session id section in the API

I can see on this link:
[http://docs.autopilot.apiary.io/#reference/api-methods/addupdate-contact ](url)

that you can do the following:

> **Finding the session id with javascript in the browser**
> In any page with the Autopilot tracking code installed, you can access the session id directly in the console:
> `var sessionId = AutopilotAnywhere.sessionId;`

When I afterwords type in the console:
`sessionId`

I get a 24 diggets id(5783626428fe359a16ac8796). So that Id I need to associate to a future contact.

But what is the exact difference on doing it this way, instead of Autopilot is taking care of it? If an anonymous visiter go to your page, and after 20 days sign up a form. In autopilot the anonymous visiter would have been associated with the history of the user, right?

So what is exact the difference between those two things? 

Best Regards.

**Comment by chrissharkey** [comment]
Hi McDuck4,

Basically we give that ID for people who want to be able to do the association in a different way. Some people, for example, add contacts via our API and want to be able to associate those added contacts with the session. So what those people do is take the ID from the browser then pass that value via AJAX back to their server-side which then issues the API call.

Really, if you don't have a use for the sessionId then you don't need to worry about it. As you say, Autopilot takes care of the association if you use our form tracker.

We include the sessionId method for people who can't or won't use the form tracker.

Hope this makes sense.

Chris.
