### ISSUE TITLE
Plans for a reporting API endpoint? 

### ISSUE THREAD

**Issue by joshdance** [autopilotdev/autopilotdev.github.io#19]
We want to pull analytic information into our platform to graph and analyze. I don't see a reporting endpoint. Is this in the works?

**Comment by chrissharkey** [comment]
Hi Josh,

Yes it is in the works! We are currently working on a new version of our API which will give you far greater access to the data that Autopilot stores. In fact, all of it! We will be releasing it in parts as each part comes online and we will have a corresponding developer portal where we write about different ways you can access and use the data.

In terms of timeline, I would expect that we will be giving beta access early next year.

I hope this helps you. It is definitely something we have been thinking a lot about and working on actively.

Chris.
