### ISSUE TITLE
Autopilot - Zoho CRM integration

### ISSUE THREAD

**Issue by FallonBorden** [autopilotdev/autopilotdev.github.io#20]
Hi everyone.
There's any way to connect Autopilot API with Zoho CRM without Zapier.
I've tried Webhooks but I don't have any progress.
Any ideas?
Thanks in advance.

**Comment by chrissharkey** [comment]
Hi Fallon,

What kind of data were you trying to get into Zoho? A full sync of contact data?

The only way to do it without coding a sync yourself using our API would be to use Zapier. Is there a reason you don't want to use it?

Chris

**Comment by FallonBorden** [comment]
I'm triying to Sync leads. I'm already using Zapier but there's a limitation by Zoho of 10 entity parameters to retrieve and other 5 custom parameters. I need to Sync more. That's why I'm trying to do it directly.
Thanks for the reply.

**Comment by chrissharkey** [comment]
Hi Fallon,

Unfortunately at this stage the only way to do it would be to write something which uses our API to pull out the contact data and writes it to Zoho's DB and visa versa. We will have a new version of our API coming out next year which will allow more and deeper integrations with other systems but for now this would be the only way to do it.

Chris.
