### ISSUE TITLE
Custom Fieild is not adding in auto pilot

### ISSUE THREAD

**Issue by swarnendumandal** [autopilotdev/autopilotdev.github.io#21]
$api_key = 'b3d7fefd9cef449e9a2fd741f90faf2d';

$data_auto_pilot = array('contact' => array('FirstName' => 'Swarenendu', 'Email' => 'earthtechnology5@gmail.com'), 'custom' => array('string--opted_out_of_email'=> 'T'));

$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, "https://api2.autopilothq.com/v1/contact");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($ch, CURLOPT_HEADER, FALSE);

	curl_setopt($ch, CURLOPT_POST, TRUE);

	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data_auto_pilot));

	curl_setopt($ch, CURLOPT_HTTPHEADER, array(
	 "autopilotapikey: $api_key",
	 "Content-Type: application/json"
	));

	$response = curl_exec($ch);
	curl_close($ch);

**Comment by NeilSmith100** [comment]
I am also able to reproduce. In this case using ZendFramework2 HTTP client

`POST /v1/trigger/0004/contact/neil+testsfaccount7@******.com HTTP/1.1
Host: api2.autopilothq.com
Connection: close
Accept-Encoding: gzip, deflate
User-Agent: Zend\Http\Client
Content-Type: application/json
Content-Length: 143
Cache-Control: no-cache
Autopilotapikey: ******************************

{
    "custom": {
        "string--password_reset_token": "1485792816:497B0ADA3902FDA849BD0CAEE4396FCFF9571013285B0E4FB6B795916F39C12E"
    }
}`

Response : 

`{"bislr_identifier":"*****","trigger_id":"0004", .... ,"custom_fields":[{"kind":"password_reset_token","value":"","fieldType":"string"}],"company_priority":false}}`

**Comment by shimmer-labs** [comment]
@swarnendumandal the Custom array is nested within the Contact array. You are exiting the Contact array before adding the Custom portion. You should have it formatted as:

$data_auto_pilot = array('contact' => array('FirstName' => 'Swarenendu', 'Email' => 'earthtechnology5@gmail.com', 'custom' => array('string--opted_out_of_email'=> 'T')));

Are you receiving an error returned with that format?

**Comment by NeilSmith100** [comment]
Confirmed I could get the email sent with custom parameter added. 

In documentation is says to "remove contact_id_or_email from URL"
Actually we need to remove all of `/contact_id_or_email` - _including the slash_

Also as per logan's comment above. the JSON should have a contact element, and a level down an array with keys 'Email' and 'custom' (with 'custom' having key : value of custom parameter)

{"contact": {"Email": "neil+testsfaccount8@****.com","custom": {"string--password_reset_token": "ABCDEF:123xyzabc"}}}

**Comment by chrissharkey** [comment]
Looks like you guys have sorted this out on your own, I really appreciate the answers here. We will be releasing the first part of our v2 API this quarter and we plan on having a much more consistent and well documented api for you to work with.
