### ISSUE TITLE
Getting potentially errant TypeMismatch errors

### ISSUE THREAD

**Issue by blakewest** [autopilotdev/autopilotdev.github.io#4]
I have been getting Type Mismatch (response code 400) errors from Autopilots API with the following message `"Bad Request" message="Type mismatch for custom field Total Sessions, expected date, provided integer">`.

I read that message as... "You told us that Total Sessions would be a date, but you gave us an integer". 

Which seems straightforward, but Total Sessions is clearly marked as being an integer in the Custom Fields section (see params below). I also checked, and all of our Contacts indeed have a Total Sessions value that is in an integer already in Autopilot (person_6125A03D-D1CC-4E3D-88DF-B52A70F39355 is one example who's value is 1. person_A45C9706-FA8E-4522-86F5-0EAB9222E10F is another example who's value is 8). Combined with [api docs](http://docs.autopilot.apiary.io/#reference/api-methods/addupdate-contact/add-or-update-contact) that say type of custom fields is enforced, and cannot be changed, I am left with the conclusion that Total Sessions has always been sent to Autopilot as an integer. I also checked the diff history of our file to confirm that Total Sessions was never, at any point, being sent as a date. So the error message potentially seems like a bug.

I replicated this bug on our development instance of Autopilot, using Contact with id: "person_D513A1DA-1388-4251-BCDA-33E872114316". I sent up the params below, and received a 400, with the message `"Bad Request" message="Type mismatch for custom field Total Sessions, expected date, provided integer">`. It seems clear to me that Total Sessions is being sent as an integer in the below params, and is indeed listed as "integer--Total--Sessions". 

Any thoughts with what's going on?

The params were:

``` ruby
{
  "Email"=>"zak+testautopilotmerge@hint.com", 
  "FirstName"=>"Katie", 
  "LastName"=>"", 
  "MobilePhone"=>nil, 
  "Company"=>"Engineering", 
  "MailingStreet"=>"921 Front Street", 
  "MailingCity"=>"San Francisco", 
  "MailingState"=>"CA", 
  "MailingPostalCode"=>"94118", 
  "MailingCountry"=>"United States", 
  "Website"=>"http://staging.hint.com", 
  "custom"=>{
    "string--User--ID"=>"user-mUODwuUnoXTi", 
    "date--User--Created"=>Fri, 07 Nov 2014 19:44:58 UTC +00:00, 
    "date--Last--Login"=>Wed, 16 Sep 2015 22:42:49 UTC +00:00, 
    ### THIS IS THE FIELD IN QUESTION ###
    "integer--Total--Sessions"=>620, 
   ##############################
    "boolean--Practice--Owner"=>false, 
    "boolean--Practice--Admin"=>true, 
    "string--Practice--ID"=>"pra-TeDmP0gqGJLZ",
      "date--Practice--Created"=>Thu, 28 Nov 2013 22:30:52 UTC +00:00, 
      "date--Practice--Launch--Date"=>nil, 
      "string--Practice--Signup--URL"=>"http://localhost:3100/signup?practice=engpractice", 
      "integer--Memberships--Estimate"=>nil, 
      "integer--Days--To--Launch"=>nil, 
      "integer--Patients"=>870, 
      "integer--Memberships"=>428, 
      "integer--Outstanding--Invoices"=>3332, 
      "float--Outstanding--Invoices--Volume"=>31693348, 
      "float--Total--TNX--Volume"=>297283, 
      "boolean--Plan--Edited"=>true, 
      "boolean--Subdomain--Edited"=>true, 
      "integer--Team--Members"=>5, 
      "integer--Locations"=>7, 
      "integer--Providers"=>8, 
      "integer--Cancellation--Reasons"=>0, 
      "integer--Coupons"=>65, 
      "integer--Charge--Items"=>6, 
      "integer--Charge--Categories"=>8, 
      "boolean--Payment--Processor--Enabled"=>true, 
      "boolean--Mailgun--Enabled"=>false, 
      "boolean--Elation--Enabled"=>true, 
      "boolean--Iora--Enabled"=>false, 
      "boolean--Cyph--Enabled"=>true, 
      "boolean--Eligible--Enabled"=>true, 
      "boolean--Liberty--Enabled"=>true
    }
  } 
```

Thanks!

**Comment by mehdivk** [comment]
@blakewest Hey mate, sorry for the late response, I checked your sandbox admin dashboard and field type for the custom field `Total Sessions` is actually `Date` and AutoPilot API does return correct error in this case.

**Comment by blakewest** [comment]
Hi @mehdivk 
I do not see Total Sessions as being a date when I log into Autopilot. See the screenshot below, but Total Sessions was clearly, at some point, accepted by Autopilot as an integer. And as I noted in the first issue comment, our params have always told Autopilot it was an integer. So I understand that in your database, it may be marked as a date, but that would in fact seem to be the bug. That somehow, it got switched from being an integer at one point, and is now a date. Thoughts?
![image](https://cloud.githubusercontent.com/assets/2524396/13546072/04120d16-e257-11e5-935e-ae58067565e7.png)

**Comment by mehdivk** [comment]
Hi @blakewest 
Per your question about type of field, we have two way of adding a custom field to our platform. One of them is via API and the other one is via dashboard. When added via API, you can't change type of custom field. On the other hand we do allow you to change type of field via dashboard. Please take a look at following screenshot that I took from dashboard of your sandbox account, it shows that type of field is Date, again we do allow you to change it back to Integer so feel free to change it if you want.

![screen shot 2016-03-07 at 4 13 38 pm](https://cloud.githubusercontent.com/assets/3216423/13561327/d8e7f5b2-e47f-11e5-993a-976592c35419.png)

For your information, we don't do any action when you change type of field via dashboard so there is no data conversion or something similar, by changing it to number you're hopefully good to go with updating contacts. We know this is not ideal to allow our clients to change type of field without any action around their existing data and we gonna fix this one soon, it's part of our plan.

Please let me know if you need more assistant in this otherwise have good day.

**Comment by blakewest** [comment]
@mehdivk hey, ok. I didn't even know that screen was there. Do you know how this got changed? Glad you guys are on top of this. It seems like this should not be allowed to be changed. But thanks for letting me know about this screen. Cheers - Blake

**Comment by mehdivk** [comment]
@blakewest Unfortunately right now we don't such a feature telling you what was change history for a given custom field but this is something that we would like to have in our platform.

**Comment by chrissharkey** [comment]
Hi Blake,

We have several updates coming for custom fields which will avoid these errors in future. I'll update this issue again when we roll them out. But for now at least we have an explanation for what is going on now.

Chris.

**Comment by chrissharkey** [comment]
Hi Blake,

We have released our custom field updates so you can now use the Autopilot Admin UI to change the type of a custom field which will make sure all contacts are set correctly. This should solve these problems completely.

Chris.

**Comment by blakewest** [comment]
Great thanks!
