### ISSUE TITLE
contacts/bookmark endpoint returns {} instead of [] on mock server

### ISSUE THREAD

**Issue by samuelckaufman** [autopilotdev/autopilotdev.github.io#5]
not sure if it's like this in prod, as we have existing contacts, but the apiary mock returns:

```
{
  "contacts": {},
  "total_contacts": 400,
  "bookmark": "person_9EAF39E4-9AEC-4134-964A-D9D8D54162E7"
}
```

For contacts/bookmark.
- Expected: an array of 400 contacts
- Actual: an empty hash

which should be an empty array rather than an empty hash.
http://docs.autopilot.apiary.io/#reference/api-methods/bulk-add-contacts/get-all-contacts?console=1

**Comment by mehdivk** [comment]
@ediblenergy Hi
I just checked `[GET] /v1/contacts` in production and can confirm that the value of `contacts` field is an array of `contact` object. I will update `apiary` docs to be the same as our production environment. 

Thank you for bringing this to our attention.

**Comment by chrissharkey** [comment]
Hi edibleenergy,

We have updated our docs to correct this.

Chris.
