### ISSUE TITLE
Return full contact details after create/update

### ISSUE THREAD

**Issue by LukaszMaslej** [autopilotdev/autopilotdev.github.io#8]
Hi,

Would it be possible to return all fields of the contact resource after create and update actions? Autopilot API returns only contact_id in response body for this actions. To check if resource is properly created/updated we need to create two requests, second to get the resource. It is a problem, specially after create because objects are available after some period of time.

**Comment by chrissharkey** [comment]
Hi Lukasz,

Thanks for the feedback. We are currently working on v2 of our API which will be able to support this. We won't be able to make the change for v1. v2 is expected to ship late this year.

Chris.
