### ISSUE TITLE
Get all contacts sorted 

### ISSUE THREAD

**Issue by LukaszMaslej** [autopilotdev/autopilotdev.github.io#9]
Hi,

Can you add possibility to sort list of contacts by last modified time in get contacts action?

**Comment by chrissharkey** [comment]
Hi Lukasz,

As mentioned in the other ticket, the v2 api will support sorting.

Chris.

**Comment by LukaszMaslej** [comment]
Hi @chrissharkey,
I would like to confirm, what is the status of new  v2 API?
